### ISSUE TITLE
pulse

### ISSUE THREAD

**Issue by mickjacobs** [ryanmjacobs/synthesizer#1]
https://github.com/ryanmjacobs/synthesizer/blob/e66848838d90f57c6cf2b3f626f2110b2d18d68a/src/clkdiv.v#L37

move line to below 29
then move 35 to below 31. remove if (mclk==00)

**Comment by ryanmjacobs** [comment]
[clkdiv.vcd.zip](https://github.com/ryanmjacobs/synthesizer/files/2065875/clkdiv.vcd.zip)

**Comment by ryanmjacobs** [comment]
[clkdiv.vcd.2.zip](https://github.com/ryanmjacobs/synthesizer/files/2065881/clkdiv.vcd.2.zip)

**Comment by ryanmjacobs** [comment]
[clkdiv.vcd.3.zip](https://github.com/ryanmjacobs/synthesizer/files/2065891/clkdiv.vcd.3.zip)
@mickjacobs 

contains waveform for mclk_max = 3 (instead of 4)
